[package]
name = "rusty-cli"
version = "0.1.0"
authors = ["escapedcat"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "7.1"