name: Rust Docs

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docs
        run: cargo doc --no-deps
